const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const LIKE = 'LIKE';
const FETCH_ALL = 'FETCH_ALL';
const START_LOADING = 'START_LOADING';
const FETCH_ERROR = 'FETCH_ERROR';
const END_LOADING = 'END_LOADING';
const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

export {
  CREATE, UPDATE, DELETE, LIKE, FETCH_ALL, FETCH_ERROR,
  START_LOADING, END_LOADING, AUTH, LOGOUT,
};
